# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TALIMGPT2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://taalimregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_92d3adfd35e64819878693673d320627 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1ea7567fa94b45d7a13d8cee449ed7aa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: taalimregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92d3adfd35e64819878693673d320627 }}/ImageTAALIMGPT:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TALIMGPT2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b0538496fa3143b9ab0a9b935b9f0c6d }}
        images: 'taalimregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_92d3adfd35e64819878693673d320627 }}/ImageTAALIMGPT:${{ github.sha }}'