# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TALIMGPT2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fruoccopublic.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_acea2f909b0b4f66a6f98d297a9fe785 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f4befb0567c842d1ad2cbe7a576c6631 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acea2f909b0b4f66a6f98d297a9fe785 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TALIMGPT2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_14e6eb37a61e452e9d60c02cc0d6aa28 }}
        images: 'fruoccopublic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_acea2f909b0b4f66a6f98d297a9fe785 }}/sample-app-aoai-chatgpt:${{ github.sha }}'