# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TAALIMGPT2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://taalimregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3a61712c94b947ee97b772371c15896e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_82e9d4443f6549ce9c7e4254bd0cbd30 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: taalimregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a61712c94b947ee97b772371c15896e }}/TAALIMIMAGE:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TAALIMGPT2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1115c3a4846d452c808ef6a54eaaae8a }}
        images: 'taalimregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a61712c94b947ee97b772371c15896e }}/TAALIMIMAGE:${{ github.sha }}'